import React, { useState } from 'react';
import { useAuth } from '../hooks/useAuth';
import { useTransactions } from '../hooks/useTransactions';
import { Card } from '../components/ui/Card';
import { User, Save, Clock, Trash2, Plus, Calendar, Settings as SettingsIcon, AlertCircle } from 'lucide-react';
import { RecurringRule, Category, TransactionType } from '../types';
import { EXPENSE_CATEGORIES, INCOME_CATEGORIES } from '../constants';

const Settings: React.FC = () => {
  const { user, updateUser } = useAuth();
  const { recurringRules, addRecurringRule, deleteRecurringRule } = useTransactions();
  
  const [displayName, setDisplayName] = useState(user?.name || '');
  const [isUpdatingProfile, setIsUpdatingProfile] = useState(false);
  const [profileMessage, setProfileMessage] = useState('');

  // Automation Form State
  const [ruleType, setRuleType] = useState<TransactionType>('expense');
  const [ruleCategory, setRuleCategory] = useState<Category>('Rent');
  const [ruleAmount, setRuleAmount] = useState('');
  const [ruleDay, setRuleDay] = useState(1);
  const [ruleNote, setRuleNote] = useState('');
  const [isAddingRule, setIsAddingRule] = useState(false);

  const handleUpdateProfile = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsUpdatingProfile(true);
    const success = await updateUser(displayName);
    if (success) {
        setProfileMessage('Profile updated successfully!');
        setTimeout(() => setProfileMessage(''), 3000);
    } else {
        setProfileMessage('Failed to update profile.');
    }
    setIsUpdatingProfile(false);
  };

  const handleAddRule = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!ruleAmount || parseFloat(ruleAmount) <= 0) {
        alert("Please enter a valid amount");
        return;
    }

    setIsAddingRule(true);
    
    const newRule: RecurringRule = {
        id: '', // Generated by Firestore
        type: ruleType,
        category: ruleCategory,
        amount: parseFloat(ruleAmount),
        dayOfMonth: ruleDay,
        note: ruleNote || (ruleType === 'income' ? 'Monthly Salary' : 'Monthly Rent'),
    };

    const success = await addRecurringRule(newRule);
    if (success) {
        setRuleAmount('');
        setRuleNote('');
    }
    setIsAddingRule(false);
  };

  return (
    <div className="space-y-8 pb-10">
      <div>
        <h2 className="text-3xl font-bold text-slate-900 tracking-tight flex items-center gap-3">
            <SettingsIcon className="w-8 h-8 text-indigo-600" />
            Settings
        </h2>
        <p className="text-slate-600 mt-2 text-lg">Manage your profile and automation preferences.</p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        {/* Profile Section */}
        <Card title="Profile Settings" subtitle="Update your personal information">
            <form onSubmit={handleUpdateProfile} className="space-y-6 mt-4">
                <div className="flex items-center gap-4 mb-6 p-4 bg-slate-50 rounded-xl border border-slate-200">
                     <div className="w-16 h-16 rounded-full bg-indigo-600 flex items-center justify-center text-white font-bold text-2xl shadow-lg shadow-indigo-200">
                        {user?.name?.charAt(0).toUpperCase()}
                     </div>
                     <div>
                        <p className="text-sm text-slate-500 font-semibold uppercase tracking-wider">Email Account</p>
                        <p className="font-bold text-slate-900 text-lg">{user?.email}</p>
                     </div>
                </div>

                <div>
                    <label className="block text-sm font-bold text-slate-700 mb-2">Display Name</label>
                    <div className="relative">
                        <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                            <User className="h-5 w-5 text-slate-500" />
                        </div>
                        <input
                            type="text"
                            value={displayName}
                            onChange={(e) => setDisplayName(e.target.value)}
                            className="block w-full pl-10 pr-4 py-3 bg-white border-2 border-slate-200 rounded-xl focus:ring-4 focus:ring-indigo-500/10 focus:border-indigo-600 outline-none text-slate-900 font-medium transition-all placeholder-slate-400"
                            placeholder="Enter your name"
                        />
                    </div>
                    <p className="text-xs text-slate-500 mt-2 ml-1">This name will appear on your dashboard.</p>
                </div>

                {profileMessage && (
                    <div className={`p-3 rounded-lg flex items-center gap-2 ${profileMessage.includes('Failed') ? 'bg-red-50 text-red-700 border border-red-200' : 'bg-emerald-50 text-emerald-700 border border-emerald-200'}`}>
                        <AlertCircle className="w-5 h-5" />
                        <span className="text-sm font-medium">{profileMessage}</span>
                    </div>
                )}

                <button 
                    type="submit" 
                    disabled={isUpdatingProfile}
                    className="w-full flex items-center justify-center px-6 py-3.5 bg-indigo-600 hover:bg-indigo-700 text-white rounded-xl font-bold text-base transition-all shadow-lg shadow-indigo-600/20 active:scale-[0.98] disabled:opacity-70 disabled:cursor-not-allowed"
                >
                    <Save className="w-5 h-5 mr-2" />
                    {isUpdatingProfile ? 'Saving Changes...' : 'Save Profile'}
                </button>
            </form>
        </Card>

        {/* Automation Section */}
        <Card title="Automation Rules" subtitle="Automatically add recurring transactions like Salary or Rent">
            <div className="space-y-6 mt-4">
                {/* Add New Rule Form */}
                <div className="bg-slate-50 p-5 rounded-2xl border border-slate-200 shadow-sm">
                    <h4 className="font-bold text-slate-900 mb-4 flex items-center gap-2">
                        <div className="p-1.5 bg-indigo-100 rounded-lg text-indigo-600"><Clock className="w-4 h-4"/></div>
                        Create New Rule
                    </h4>
                    <form onSubmit={handleAddRule} className="space-y-4">
                        <div className="grid grid-cols-2 gap-4">
                             <div>
                                <label className="block text-xs font-bold text-slate-600 uppercase tracking-wide mb-1.5">Type</label>
                                <select 
                                    value={ruleType} 
                                    onChange={(e) => {
                                        setRuleType(e.target.value as TransactionType);
                                        setRuleCategory(e.target.value === 'income' ? 'Salary' : 'Rent');
                                    }}
                                    className="w-full p-2.5 bg-white border border-slate-300 rounded-xl text-sm font-semibold text-slate-900 focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-600 outline-none transition-colors"
                                >
                                    <option value="income">Income (+)</option>
                                    <option value="expense">Expense (-)</option>
                                </select>
                             </div>
                             <div>
                                <label className="block text-xs font-bold text-slate-600 uppercase tracking-wide mb-1.5">Category</label>
                                <select 
                                    value={ruleCategory} 
                                    onChange={(e) => setRuleCategory(e.target.value as Category)}
                                    className="w-full p-2.5 bg-white border border-slate-300 rounded-xl text-sm font-semibold text-slate-900 focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-600 outline-none transition-colors"
                                >
                                    {(ruleType === 'income' ? INCOME_CATEGORIES : EXPENSE_CATEGORIES).map(c => (
                                        <option key={c} value={c}>{c}</option>
                                    ))}
                                </select>
                             </div>
                        </div>
                        
                        <div className="grid grid-cols-2 gap-4">
                            <div>
                                <label className="block text-xs font-bold text-slate-600 uppercase tracking-wide mb-1.5">Amount (₹)</label>
                                <input 
                                    type="number" 
                                    required
                                    value={ruleAmount}
                                    onChange={(e) => setRuleAmount(e.target.value)}
                                    placeholder="0.00"
                                    className="w-full p-2.5 bg-white border border-slate-300 rounded-xl text-sm font-bold text-slate-900 placeholder-slate-400 focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-600 outline-none transition-colors"
                                />
                            </div>
                            <div>
                                <label className="block text-xs font-bold text-slate-600 uppercase tracking-wide mb-1.5">Day of Month</label>
                                <select 
                                    value={ruleDay} 
                                    onChange={(e) => setRuleDay(parseInt(e.target.value))}
                                    className="w-full p-2.5 bg-white border border-slate-300 rounded-xl text-sm font-semibold text-slate-900 focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-600 outline-none transition-colors"
                                >
                                    {Array.from({length: 31}, (_, i) => i + 1).map(d => (
                                        <option key={d} value={d}>{d}{[1, 21, 31].includes(d) ? 'st' : [2, 22].includes(d) ? 'nd' : [3, 23].includes(d) ? 'rd' : 'th'}</option>
                                    ))}
                                </select>
                            </div>
                        </div>

                        <div>
                            <label className="block text-xs font-bold text-slate-600 uppercase tracking-wide mb-1.5">Description</label>
                            <input 
                                type="text"
                                value={ruleNote}
                                onChange={(e) => setRuleNote(e.target.value)}
                                placeholder={ruleType === 'income' ? "e.g., Monthly Salary" : "e.g., Apartment Rent"}
                                className="w-full p-2.5 bg-white border border-slate-300 rounded-xl text-sm font-medium text-slate-900 placeholder-slate-400 focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-600 outline-none transition-colors"
                            />
                        </div>

                        <button 
                            type="submit" 
                            disabled={isAddingRule}
                            className="w-full py-3 bg-white border-2 border-dashed border-indigo-300 text-indigo-700 rounded-xl hover:bg-indigo-50 hover:border-indigo-500 font-bold transition-all flex items-center justify-center gap-2 active:scale-[0.98]"
                        >
                            <Plus className="w-5 h-5" />
                            {isAddingRule ? 'Adding...' : 'Add Automation Rule'}
                        </button>
                    </form>
                </div>

                <div className="space-y-4">
                    <h4 className="font-bold text-slate-800 flex items-center gap-2">
                        <div className="w-2 h-6 bg-indigo-600 rounded-full"></div>
                        Active Automations ({recurringRules.length})
                    </h4>
                    {recurringRules.length === 0 ? (
                        <div className="text-center py-8 bg-slate-50 rounded-2xl border border-slate-100 border-dashed">
                             <Clock className="w-10 h-10 text-slate-300 mx-auto mb-2" />
                             <p className="text-slate-500 font-medium">No recurring rules yet.</p>
                             <p className="text-xs text-slate-400 mt-1">Add a rule above to get started.</p>
                        </div>
                    ) : (
                        <div className="space-y-3">
                            {recurringRules.map(rule => (
                                <div key={rule.id} className="group flex items-center justify-between p-4 bg-white border border-slate-200 rounded-2xl shadow-sm hover:shadow-md transition-all hover:border-indigo-200">
                                    <div className="flex items-center gap-4">
                                        <div className={`w-12 h-12 rounded-xl flex items-center justify-center shrink-0 ${rule.type === 'income' ? 'bg-emerald-100 text-emerald-600' : 'bg-rose-100 text-rose-600'}`}>
                                            <Calendar className="w-6 h-6" />
                                        </div>
                                        <div>
                                            <p className="font-bold text-slate-900 text-base">{rule.note}</p>
                                            <div className="flex items-center gap-2 mt-0.5">
                                                <span className={`text-xs font-bold px-2 py-0.5 rounded-md ${rule.type === 'income' ? 'bg-emerald-50 text-emerald-700' : 'bg-rose-50 text-rose-700'}`}>
                                                    {rule.category}
                                                </span>
                                                <span className="text-xs text-slate-500 font-medium">
                                                    Runs on the {rule.dayOfMonth}{[1, 21, 31].includes(rule.dayOfMonth) ? 'st' : [2, 22].includes(rule.dayOfMonth) ? 'nd' : [3, 23].includes(rule.dayOfMonth) ? 'rd' : 'th'}
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                    <div className="flex flex-col items-end gap-2">
                                        <span className={`font-bold text-lg ${rule.type === 'income' ? 'text-emerald-600' : 'text-slate-900'}`}>
                                            {rule.type === 'income' ? '+' : '-'}₹{rule.amount.toLocaleString()}
                                        </span>
                                        <button 
                                            onClick={() => deleteRecurringRule(rule.id)}
                                            className="p-2 text-slate-400 hover:text-red-600 hover:bg-red-50 rounded-lg transition-colors"
                                            title="Delete Rule"
                                        >
                                            <Trash2 className="w-5 h-5" />
                                        </button>
                                    </div>
                                </div>
                            ))}
                        </div>
                    )}
                </div>
            </div>
        </Card>
      </div>
    </div>
  );
};

export default Settings;